export const I18N_VERSION='1.5';
export const SUPPORTED_LOCALES=Object.freeze({en:{label:'English',native:'English'},de:{label:'German',native:'Deutsch'},it:{label:'Italian',native:'Italiano'},fr:{label:'French',native:'Français'},es:{label:'Spanish',native:'Español'},pt:{label:'Portuguese',native:'Português'},uk:{label:'Ukrainian',native:'Українська'},pl:{label:'Polish',native:'Polski'},tr:{label:'Turkish',native:'Türkçe'},ja:{label:'Japanese',native:'日本語'},ko:{label:'Korean',native:'한국어'},zh:{label:'Chinese',native:'中文'}});
const T={
'Command Center':{de:'Kommandozentrale',it:'Centro di comando',fr:'Centre de commandement',es:'Centro de mando',pt:'Centro de comando',uk:'Центр керування',pl:'Centrum dowodzenia',tr:'Komuta Merkezi',ja:'コマンドセンター',ko:'커맨드 센터',zh:'指挥中心'},
'Cases':{de:'Fälle',it:'Casi',fr:'Dossiers',es:'Casos',pt:'Casos',uk:'Справи',pl:'Sprawy',tr:'Vakalar',ja:'ケース',ko:'사례',zh:'案件'},
'Evidence':{de:'Beweise',it:'Prove',fr:'Preuves',es:'Evidencias',pt:'Evidências',uk:'Докази',pl:'Dowody',tr:'Kanıtlar',ja:'証拠',ko:'증거',zh:'证据'},
'Entities & Graph':{de:'Entitäten & Graph',it:'Entità & Grafo',fr:'Entités & Graphe',es:'Entidades y grafo',pt:'Entidades e grafo',uk:'Сутності та граф',pl:'Encje i graf',tr:'Varlıklar ve grafik',ja:'エンティティとグラフ',ko:'엔터티 및 그래프',zh:'实体与图'},
'Hypotheses':{de:'Hypothesen',it:'Ipotesi',fr:'Hypothèses',es:'Hipótesis',pt:'Hipóteses',uk:'Гіпотези',pl:'Hipotezy',tr:'Hipotezler',ja:'仮説',ko:'가설',zh:'假设'},
'Contradictions':{de:'Widersprüche',it:'Contraddizioni',fr:'Contradictions',es:'Contradicciones',pt:'Contradições',uk:'Суперечності',pl:'Sprzeczności',tr:'Çelişkiler',ja:'矛盾',ko:'모순',zh:'矛盾'},
'Reports':{de:'Berichte',it:'Report',fr:'Rapports',es:'Informes',pt:'Relatórios',uk:'Звіти',pl:'Raporty',tr:'Raporlar',ja:'レポート',ko:'보고서',zh:'报告'},
'Governance':{de:'Governance',it:'Governance',fr:'Gouvernance',es:'Gobernanza',pt:'Governança',uk:'Управління',pl:'Zarządzanie',tr:'Yönetişim',ja:'ガバナンス',ko:'거버넌스',zh:'治理'},
'Search':{de:'Suchen',it:'Cerca',fr:'Rechercher',es:'Buscar',pt:'Pesquisar',uk:'Пошук',pl:'Szukaj',tr:'Ara',ja:'検索',ko:'검색',zh:'搜索'},
'OSINT Utility Lab':{de:'OSINT-Werkzeuglabor',it:'Laboratorio strumenti OSINT',fr:'Laboratoire d’outils OSINT',es:'Laboratorio de herramientas OSINT',pt:'Laboratório de ferramentas OSINT',uk:'Лабораторія інструментів OSINT',pl:'Laboratorium narzędzi OSINT',tr:'OSINT Araç Laboratuvarı',ja:'OSINTツールラボ',ko:'OSINT 도구 연구실',zh:'OSINT 工具实验室'},
'Forensics / Signal Lab':{de:'Forensik / Signallabor',it:'Forensics / Laboratorio segnali',fr:'Forensique / Laboratoire des signaux',es:'Forense / Laboratorio de señales',pt:'Forense / Laboratório de sinais',uk:'Форензика / Лабораторія сигналів',pl:'Forensics / Laboratorium sygnałów',tr:'Adli Analiz / Sinyal Laboratuvarı',ja:'フォレンジック / シグナルラボ',ko:'포렌식 / 신호 연구실',zh:'取证 / 信号实验室'},
'FORENSICS / SIGNAL LAB':{de:'FORENSIK / SIGNALLAB',it:'FORENSICS / LABORATORIO SEGNALI',fr:'FORENSIQUE / LABORATOIRE DES SIGNAUX',es:'FORENSE / LABORATORIO DE SEÑALES',pt:'FORENSE / LABORATÓRIO DE SINAIS',uk:'ФОРЕНЗИКА / ЛАБОРАТОРІЯ СИГНАЛІВ',pl:'FORENSICS / LABORATORIUM SYGNAŁÓW',tr:'ADLİ ANALİZ / SİNYAL LABORATUVARI',ja:'フォレンジック / シグナルラボ',ko:'포렌식 / 신호 연구실',zh:'取证 / 信号实验室'},
'Local-first':{de:'Lokal zuerst',it:'Locale prima',fr:'Local en priorité',es:'Local primero',pt:'Local primeiro',uk:'Локально в першу черу',pl:'Lokalnie przede wszystkim',tr:'Önce yerel',ja:'ローカル優先',ko:'로컬 우선',zh:'本地优先'},
'LOCAL-FIRST':{de:'LOKAL-PRIORITÄT',it:'PRIMA LOCALE',fr:'LOCAL EN PRIORITÉ',es:'LOCAL PRIMERO',pt:'LOCAL PRIMEIRO',uk:'ЛОКАЛЬНО ПЕРШЕ',pl:'LOKALNIE',tr:'ÖNCE YEREL',ja:'ローカル優先',ko:'로컬 우선',zh:'本地优先'},
'PERSISTED':{de:'GESPEICHERT',it:'SALVATO',fr:'ENREGISTRÉ',es:'GUARDADO',pt:'GUARDADO',uk:'ЗБЕРЕЖЕНО',pl:'ZAPISANO',tr:'KAYDEDİLDİ',ja:'保存済み',ko:'저장됨',zh:'已保存'},
'KNOWN':{de:'BEKANNT',it:'NOTO',fr:'CONNU',es:'CONOCIDO',pt:'CONHECIDO',uk:'ВІДОМО',pl:'ZNANE',tr:'BİLİNEN',ja:'既知',ko:'알려짐',zh:'已知'},
'INFERRED':{de:'ABGELEITET',it:'INFERITO',fr:'DÉDUIT',es:'INFERIDO',pt:'INFERIDO',uk:'ВИВЕДЕНО',pl:'WNIOSKOWANE',tr:'ÇIKARILMIŞ',ja:'推論',ko:'추론됨',zh:'推断'},
'UNKNOWN':{de:'UNBEKANNT',it:'SCONOSCIUTO',fr:'INCONNU',es:'DESCONOCIDO',pt:'DESCONHECIDO',uk:'НЕВІДОМО',pl:'NIEZNANE',tr:'BİLİNMİYOR',ja:'未知',ko:'알 수 없음',zh:'未知'},
'NEXT BEST ACTION':{de:'NÄCHSTE BESTE AKTION',it:'PROSSIMA AZIONE MIGLIORE',fr:'PROCHAINE MEILLEURE ACTION',es:'PRÓXIMA MEJOR ACCIÓN',pt:'PRÓXIMA MELHOR AÇÃO',uk:'НАСТУПНА КРАЩА ДІЯ',pl:'NAJLEPSZE NASTĘPNE DZIAŁANIE',tr:'SONRAKİ EN İYİ EYLEM',ja:'次善のアクション',ko:'다음 최선의 조치',zh:'下一步最佳行动'}
};
const KEY='occ.locale';
export function supportedLocales(){return Object.keys(SUPPORTED_LOCALES);}
export function getLocale(storage=globalThis.localStorage){try{const saved=storage?.getItem(KEY);if(saved&&SUPPORTED_LOCALES[saved])return saved;}catch{}const browser=typeof navigator!=='undefined'?(navigator.language||'').toLowerCase().split('-')[0]:'';return SUPPORTED_LOCALES[browser]?browser:'en';}
export function translate(value,locale=getLocale()){const text=String(value??'');if(locale==='en')return text;return T[text]?.[locale]||text;}
export function setLocale(locale,storage=globalThis.localStorage){if(!SUPPORTED_LOCALES[locale])throw new Error(`Unsupported locale: ${locale}`);try{storage?.setItem(KEY,locale);}catch{}if(typeof document!=='undefined'){document.documentElement.lang=locale;document.dispatchEvent(new CustomEvent('occ:locale',{detail:{locale}}));}return locale;}
function installSelector(){if(typeof document==='undefined')return;let wrap=document.getElementById('languageControl');let select=document.getElementById('localeSelect');if(wrap&&select){select.value=getLocale();return;}const host=document.querySelector('.status')||document.querySelector('.top')||document.body;if(!host)return;wrap=document.createElement('div');wrap.id='languageControl';wrap.setAttribute('aria-label','Interface language');wrap.title='Choose interface language';wrap.style.cssText='display:inline-flex;align-items:center;gap:5px;margin-left:10px;padding:3px 6px;border:1px solid #69d7d0;border-radius:999px;background:#071318;color:#e9f4f4;font:11px/1 system-ui,sans-serif;vertical-align:middle;position:relative;z-index:50;box-shadow:0 0 14px #69d7d018';const icon=document.createElement('span');icon.textContent='🌐';icon.setAttribute('aria-hidden','true');icon.style.cssText='font-size:14px;line-height:1';const label=document.createElement('span');label.textContent='LANG';label.style.cssText='color:#69d7d0;font-weight:800;font-size:9px;letter-spacing:.08em';select=document.createElement('select');select.id='localeSelect';select.setAttribute('aria-label','Choose interface language');select.style.cssText='appearance:auto;background:#071318;color:#e9f4f4;border:0;outline:0;border-radius:5px;padding:4px 20px 4px 4px;font-size:11px;font-weight:700;min-width:88px;cursor:pointer';for(const code of supportedLocales()){const o=document.createElement('option');o.value=code;o.textContent=`${SUPPORTED_LOCALES[code].native} · ${code.toUpperCase()}`;select.appendChild(o);}select.value=getLocale();select.addEventListener('change',()=>setLocale(select.value));wrap.append(icon,label,select);const status=host.classList?.contains('status')?host:host.querySelector('.status');if(status)status.appendChild(wrap);else host.appendChild(wrap);}
const originalText=new WeakMap();
export function translateDom(){if(typeof document==='undefined'||!document.body)return;const locale=getLocale();document.documentElement.lang=locale;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('#localeSelect,#languageControl'))continue;const raw=originalText.has(node)?originalText.get(node):node.nodeValue;originalText.set(node,raw);const trimmed=String(raw).trim();if(!trimmed)continue;const translated=translate(trimmed,locale);const lead=String(raw).match(/^\s*/)?.[0]||'',trail=String(raw).match(/\s*$/)?.[0]||'';const next=lead+translated+trail;if(node.nodeValue!==next)node.nodeValue=next;}}
function boot(){installSelector();translateDom();document.addEventListener('occ:locale',()=>{installSelector();requestAnimationFrame(translateDom);setTimeout(translateDom,60);});let tries=0;const ensure=()=>{if(document.getElementById('localeSelect'))return;if(tries++<40){installSelector();setTimeout(ensure,250);}};ensure();const observer=new MutationObserver(()=>{installSelector();translateDom();});observer.observe(document.body,{childList:true,subtree:true});import('../daid-ui.js').catch(()=>{});import('../tools/forensics-ui.js').catch(()=>{});}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}