/**
 * Professional i18n — key-based, re-render friendly.
 * English is the canonical UI language. Evidence keeps its original language.
 */
export const I18N_VERSION='3.0';
export const SUPPORTED_LOCALES=Object.freeze({
  en:{label:'English',native:'English',dir:'ltr'},de:{label:'German',native:'Deutsch',dir:'ltr'},it:{label:'Italian',native:'Italiano',dir:'ltr'},fr:{label:'French',native:'Français',dir:'ltr'},es:{label:'Spanish',native:'Español',dir:'ltr'},pt:{label:'Portuguese',native:'Português',dir:'ltr'},uk:{label:'Ukrainian',native:'Українська',dir:'ltr'},pl:{label:'Polish',native:'Polski',dir:'ltr'},tr:{label:'Turkish',native:'Türkçe',dir:'ltr'},ja:{label:'Japanese',native:'日本語',dir:'ltr'},ko:{label:'Korean',native:'한국어',dir:'ltr'},zh:{label:'Chinese',native:'中文',dir:'ltr'}
});
const STORAGE_KEY='occ.locale.v3';
const DICT={
'nav.command':{en:'Command Center',de:'Kommandozentrale',it:'Centro di Comando',fr:'Centre de commandement',es:'Centro de mando',pt:'Centro de Comando',uk:'Центр командування',pl:'Centrum dowodzenia',tr:'Komuta Merkezi',ja:'コマンドセンター',ko:'커맨드 센터',zh:'指挥中心'},
'nav.cases':{en:'Cases',de:'Fälle',it:'Casi',fr:'Dossiers',es:'Casos',pt:'Casos',uk:'Справи',pl:'Sprawy',tr:'Vakalar',ja:'案件',ko:'사건',zh:'案件'},
'nav.evidence':{en:'Evidence',de:'Beweise',it:'Prove',fr:'Preuves',es:'Evidencias',pt:'Evidências',uk:'Докази',pl:'Dowody',tr:'Kanıtlar',ja:'証拠',ko:'증거',zh:'证据'},
'nav.entities':{en:'Entities & Graph',de:'Entitäten & Graph',it:'Entità e Grafo',fr:'Entités & Graphe',es:'Entidades y grafo',pt:'Entidades e grafo',uk:'Сутності та граф',pl:'Encje i graf',tr:'Varlıklar ve Grafik',ja:'エンティティとグラフ',ko:'엔터티 및 그래프',zh:'实体与图谱'},
'nav.hypotheses':{en:'Hypotheses',de:'Hypothesen',it:'Ipotesi',fr:'Hypothèses',es:'Hipótesis',pt:'Hipóteses',uk:'Гіпотези',pl:'Hipotezy',tr:'Hipotezler',ja:'仮説',ko:'가설',zh:'假设'},
'nav.contradictions':{en:'Contradictions',de:'Widersprüche',it:'Contraddizioni',fr:'Contradictions',es:'Contradicciones',pt:'Contradições',uk:'Суперечності',pl:'Sprzeczności',tr:'Çelişkiler',ja:'矛盾',ko:'모순',zh:'矛盾'},
'nav.reports':{en:'Reports',de:'Berichte',it:'Report',fr:'Rapports',es:'Informes',pt:'Relatórios',uk:'Звіти',pl:'Raporty',tr:'Raporlar',ja:'レポート',ko:'보고서',zh:'报告'},
'nav.governance':{en:'Governance',de:'Governance',it:'Governance',fr:'Gouvernance',es:'Gobernanza',pt:'Governança',uk:'Управління',pl:'Nadzór',tr:'Yönetişim',ja:'ガバナンス',ko:'거버넌스',zh:'治理'},
'brand.living':{en:'LIVING ANALYST COCKPIT',de:'LEBENDIGES ANALYSTEN-COCKPIT',it:'COCKPIT ANALISTA VIVO',fr:'COCKPIT ANALYSTE VIVANT',es:'COCKPIT ANALISTA VIVO',pt:'COCKPIT DE ANALISTA VIVO',uk:'ЖИВИЙ АНАЛІТИЧНИЙ КОКПІТ',pl:'ŻYWY KOKPIT ANALITYKA',tr:'CANLI ANALİST KOKPİTİ',ja:'ライブ分析コックピット',ko:'실시간 분석가 콕핏',zh:'实时分析驾驶舱'},
'search.placeholder':{en:'Search the workspace…',de:'Workspace durchsuchen…',it:'Cerca nel workspace…',fr:'Rechercher…',es:'Buscar…',pt:'Pesquisar no workspace…',uk:'Пошук у робочому просторі…',pl:'Szukaj w obszarze roboczym…',tr:'Çalışma alanında ara…',ja:'ワークスペースを検索…',ko:'워크스페이스 검색…',zh:'搜索工作区…'},
'focus.none':{en:'No active case',de:'Kein aktiver Fall',it:'Nessun caso attivo',fr:'Aucun dossier actif',es:'Ningún caso activo',pt:'Nenhum caso ativo',uk:'Немає активної справи',pl:'Brak aktywnej sprawy',tr:'Etkin vaka yok',ja:'アクティブな案件なし',ko:'활성 사건 없음',zh:'没有活动案件'},
'focus.clear':{en:'Clear focus',de:'Fokus aufheben',it:'Rimuovi focus',fr:'Effacer le focus',es:'Quitar enfoque',pt:'Limpar foco',uk:'Очистити фокус',pl:'Wyczyść fokus',tr:'Odağı temizle',ja:'フォーカス解除',ko:'포커스 해제',zh:'清除焦点'},
'focus.new':{en:'+ New case',de:'+ Neuer Fall',it:'+ Nuovo caso',fr:'+ Nouveau dossier',es:'+ Nuevo caso',pt:'+ Novo caso',uk:'+ Нова справа',pl:'+ Nowa sprawa',tr:'+ Yeni vaka',ja:'+ 新規案件',ko:'+ 새 사건',zh:'+ 新建案件'},
'focus.create':{en:'+ New investigation',de:'+ Neue Untersuchung',it:'+ Nuova indagine',fr:'+ Nouvelle enquête',es:'+ Nueva investigación',pt:'+ Nova investigação',uk:'+ Нове розслідування',pl:'+ Nowe dochodzenie',tr:'+ Yeni soruşturma',ja:'+ 新規調査',ko:'+ 새 조사',zh:'+ 新建调查'},
'action.new.investigation':{en:'+ New investigation',de:'+ Neue Untersuchung',it:'+ Nuova indagine',fr:'+ Nouvelle enquête',es:'+ Nueva investigación',pt:'+ Nova investigação',uk:'+ Нове розслідування',pl:'+ Nowe dochodzenie',tr:'+ Yeni soruşturma',ja:'+ 新規調査',ko:'+ 새 조사',zh:'+ 新建调查'},
'action.new.evidence':{en:'+ Add evidence',de:'+ Beweis hinzufügen',it:'+ Aggiungi prova',fr:'+ Ajouter une preuve',es:'+ Añadir evidencia',pt:'+ Adicionar evidência',uk:'+ Додати доказ',pl:'+ Dodaj dowód',tr:'+ Kanıt ekle',ja:'+ 証拠を追加',ko:'+ 증거 추가',zh:'+ 添加证据'},
'action.new.entity':{en:'+ Entity',de:'+ Entität',it:'+ Entità',fr:'+ Entité',es:'+ Entidad',pt:'+ Entidade',uk:'+ Сутність',pl:'+ Encja',tr:'+ Varlık',ja:'+ エンティティ',ko:'+ 엔터티',zh:'+ 实体'},
'action.new.hypothesis':{en:'+ Add hypothesis',de:'+ Hypothese hinzufügen',it:'+ Aggiungi ipotesi',fr:'+ Ajouter une hypothèse',es:'+ Añadir hipótesis',pt:'+ Adicionar hipótese',uk:'+ Додати гіпотезу',pl:'+ Dodaj hipotezę',tr:'+ Hipotez ekle',ja:'+ 仮説を追加',ko:'+ 가설 추가',zh:'+ 添加假设'},
'action.new.relationship':{en:'+ Relationship',de:'+ Beziehung',it:'+ Relazione',fr:'+ Relation',es:'+ Relación',pt:'+ Relação',uk:'+ Зв’язок',pl:'+ Relacja',tr:'+ İlişki',ja:'+ 関係',ko:'+ 관계',zh:'+ 关系'},
'action.triage':{en:'Run contradiction triage',de:'Widerspruchs-Triage',it:'Esegui triage contraddizioni',fr:'Triage des contradictions',es:'Triage de contradicciones',pt:'Triagem de contradições',uk:'Тріаж суперечностей',pl:'Triage sprzeczności',tr:'Çelişki triyajı',ja:'矛盾トリアージ',ko:'모순 트리아지',zh:'矛盾分诊'},
'action.report':{en:'Create professional report',de:'Professionellen Bericht erstellen',it:'Crea report professionale',fr:'Créer un rapport professionnel',es:'Crear informe profesional',pt:'Criar relatório profissional',uk:'Створити професійний звіт',pl:'Utwórz raport profesjonalny',tr:'Profesyonel rapor oluştur',ja:'専門レポートを作成',ko:'전문 보고서 생성',zh:'创建专业报告'},
'modal.cancel':{en:'Cancel',de:'Abbrechen',it:'Annulla',fr:'Annuler',es:'Cancelar',pt:'Cancelar',uk:'Скасувати',pl:'Anuluj',tr:'İptal',ja:'キャンセル',ko:'취소',zh:'取消'},
'modal.create':{en:'Create',de:'Erstellen',it:'Crea',fr:'Créer',es:'Crear',pt:'Criar',uk:'Створити',pl:'Utwórz',tr:'Oluştur',ja:'作成',ko:'생성',zh:'创建'},
'live.title':{en:'Live public-source feeds',de:'Live-öffentliche Quellen',it:'Feed pubblici in tempo reale',fr:'Flux publics en direct',es:'Feeds públicos en vivo',pt:'Fontes públicas ao vivo',uk:'Публічні джерела наживо',pl:'Źródła publiczne na żywo',tr:'Canlı açık kaynak akışları',ja:'公開ソースのライブフィード',ko:'실시간 공개 소스 피드',zh:'实时公开来源'},
'live.principle':{en:'ONLINE DATA ≠ VERIFIED EVIDENCE · Results stay RAW until human review.',de:'ONLINE-DATEN ≠ VERIFIZIERTER BEWEIS · Ergebnisse bleiben RAW bis zur Prüfung.',it:'DATI ONLINE ≠ PROVA VERIFICATA · I risultati restano RAW fino a revisione umana.',fr:'DONNÉES EN LIGNE ≠ PREUVE VÉRIFIÉE · Les résultats restent bruts jusqu’à vérification.',es:'DATOS EN LÍNEA ≠ EVIDENCIA VERIFICADA · Los resultados siguen en bruto hasta revisión.',pt:'DADOS ONLINE ≠ EVIDÊNCIA VERIFICADA · Os resultados permanecem brutos até revisão.',uk:'ОНЛАЙН-ДАНІ ≠ ПЕРЕВІРЕНИЙ ДОКАЗ · Результати залишаються сирими до перевірки.',pl:'DANE ONLINE ≠ ZWERYFIKOWANY DOWÓD · Wyniki pozostają surowe do weryfikacji.',tr:'ÇEVRİMİÇİ VERİ ≠ DOĞRULANMIŞ KANIT · Sonuçlar incelemeye kadar HAM kalır.',ja:'オンラインデータ ≠ 検証済み証拠 · 結果は人手確認までRAWのままです。',ko:'온라인 데이터 ≠ 검증된 증거 · 결과는 사람의 검토 전까지 RAW로 유지됩니다.',zh:'在线数据 ≠ 已验证证据 · 结果在人工审查前保持原始状态。'}
};
const FREE={};
export function supportedLocales(){return Object.keys(SUPPORTED_LOCALES);}
export function getLocale(storage=globalThis.localStorage){try{const saved=storage?.getItem(STORAGE_KEY);if(saved&&SUPPORTED_LOCALES[saved])return saved;}catch{}const browser=(typeof navigator!=='undefined'?(navigator.language||''):'').toLowerCase().split('-')[0];return SUPPORTED_LOCALES[browser]?browser:'en';}
export function t(key,locale=getLocale()){const entry=DICT[key];return entry?(entry[locale]||entry.en||key):key;}
export function translate(value,locale=getLocale()){const text=String(value??'');if(locale==='en')return text;if(FREE[text]?.[locale])return FREE[text][locale];for(const entry of Object.values(DICT)){if(entry.en===text&&entry[locale])return entry[locale];}return text;}
export function setLocale(locale,storage=globalThis.localStorage){if(!SUPPORTED_LOCALES[locale])throw new Error(`Unsupported locale: ${locale}`);try{storage?.setItem(STORAGE_KEY,locale);}catch{}if(typeof document!=='undefined'){document.documentElement.lang=locale;document.documentElement.dir=SUPPORTED_LOCALES[locale].dir||'ltr';document.dispatchEvent(new CustomEvent('occ:locale',{detail:{locale}}));}return locale;}
export function installLanguageSelector(){if(typeof document==='undefined')return;let wrap=document.getElementById('languageControl');if(wrap){const select=document.getElementById('localeSelect');if(select)select.value=getLocale();return;}const host=document.querySelector('.status')||document.querySelector('.top')||document.body;if(!host)return;wrap=document.createElement('div');wrap.id='languageControl';wrap.style.cssText='display:inline-flex;align-items:center;gap:6px;margin-left:8px;padding:6px 10px;border:1px solid #69d7d0;border-radius:999px;background:#071318;font:12px/1 system-ui,sans-serif;z-index:50;min-height:36px';const icon=document.createElement('span');icon.textContent='🌐';icon.style.fontSize='16px';const select=document.createElement('select');select.id='localeSelect';select.setAttribute('aria-label','Interface language');select.style.cssText='appearance:auto;background:#071318;color:#e9f4f4;border:0;outline:0;border-radius:5px;padding:4px 20px 4px 2px;font-size:13px;font-weight:700;min-width:96px;min-height:32px;cursor:pointer';for(const code of supportedLocales()){const o=document.createElement('option');o.value=code;o.textContent=SUPPORTED_LOCALES[code].native;select.appendChild(o);}select.value=getLocale();select.addEventListener('change',()=>{setLocale(select.value);window.dispatchEvent(new CustomEvent('occ:re-render'));});wrap.append(icon,select);host.appendChild(wrap);}
export function bootI18n(){if(typeof document==='undefined')return;document.documentElement.lang=getLocale();installLanguageSelector();document.addEventListener('occ:locale',()=>installLanguageSelector());}
