import { buildDAID2 } from './daid2.js';
const clamp01 = value => Math.max(0, Math.min(1, Number(value) || 0));
const unique = values => [...new Set(values.filter(Boolean))];
function sourceIdentity(source){if(!source)return 'unknown';return source.independenceGroup||source.parentSourceId||source.publisher||source.id;}
export function buildIntelligenceMatrix(state={}){
 const sources=state.sources||[],evidence=state.evidence||[],entities=state.entities||[],relationships=state.relationships||[],hypotheses=state.hypotheses||[],contradictions=state.contradictions||[],decisions=state.decisions||[];
 if(!sources.length&&!evidence.length&&!entities.length&&!relationships.length&&!hypotheses.length&&!contradictions.length&&!decisions.length){const base={nodes:[],trace:[],gaps:[{code:'NO_EVIDENCE',severity:'high',message:'No source-backed evidence has entered the matrix.'}],integrity:0,counts:{sources:0,evidence:0,entities:0,relationships:0,hypotheses:0,contradictions:0,decisions:0,verified:0,independentGroups:0},nextAction:'Create an investigation objective and capture the first source-backed claim.'};return {...base,daid2:buildDAID2(state,base)};}
 const sourceById=new Map(sources.map(x=>[x.id,x])),evidenceById=new Map(evidence.map(x=>[x.id,x])),entityById=new Map(entities.map(x=>[x.id,x])),hypothesisById=new Map(hypotheses.map(x=>[x.id,x]));
 const sourceScore=src=>clamp01(src?.reliability??.5);const evidenceScore=ev=>{const base=clamp01(ev?.confidence),verification=ev?.humanVerified?1:ev?.status==='FACT'?.85:ev?.status==='CONTESTED'?.25:.55;return clamp01(base*.65+verification*.35);};const getSourceIds=ev=>unique([...(Array.isArray(ev?.sourceIds)?ev.sourceIds:[]),ev?.sourceId]);
 const trace=evidence.map(ev=>{const ids=getSourceIds(ev),linkedSources=ids.map(id=>sourceById.get(id)).filter(Boolean),groups=unique(linkedSources.map(sourceIdentity)),corroborating=(ev.corroboratingSourceIds||[]).map(id=>sourceById.get(id)).filter(Boolean),contradicting=(ev.contradictingSourceIds||[]).map(id=>sourceById.get(id)).filter(Boolean);return {evidenceId:ev.id,title:ev.title,claim:ev.claim,whatProves:ev.whatProves||'',doesNotProve:ev.doesNotProve||'',status:ev.status,confidence:evidenceScore(ev),sourceIds:ids,sourceCount:linkedSources.length,independentSourceGroups:groups.length,sources:linkedSources.map(s=>({id:s.id,name:s.name,type:s.type,url:s.url||s.locator||'',publisher:s.publisher||'',author:s.author||'',publishedAt:s.publishedAt||'',accessedAt:s.accessedAt||s.capturedAt||'',reliability:sourceScore(s),independenceGroup:sourceIdentity(s),derivedFrom:s.parentSourceId||'',provenance:s.provenance||''})),corroborating:corroborating.map(s=>s.id),contradicting:contradicting.map(s=>s.id)};});
 const evidenceLinks=trace.map(t=>{const source=t.sources[0];return {type:'EVIDENCE',id:t.evidenceId,label:t.title,status:t.status,confidence:clamp01(t.confidence*(.65+(source?.reliability||.5)*.35)),sourceId:source?.id||null,source:source?.name||'Unknown source'};});
 const relationshipLinks=relationships.map(rel=>{const a=entityById.get(rel.fromEntityId),b=entityById.get(rel.toEntityId),support=(rel.evidenceIds||[]).map(id=>evidenceById.get(id)).filter(Boolean),confidence=support.length?support.reduce((sum,ev)=>sum+evidenceScore(ev),0)/support.length:clamp01(rel.confidence);return {type:'RELATIONSHIP',id:rel.id,label:`${a?.name||'?'} → ${b?.name||'?'}`,confidence:clamp01(confidence*.8+clamp01(rel.confidence)*.2),evidenceIds:support.map(x=>x.id)};});
 const hypothesisLinks=hypotheses.map(h=>{const supporting=[...(h.evidenceFor||[]),...(h.evidenceAgainst||[])].map(id=>evidenceById.get(id)).filter(Boolean),supportScore=supporting.length?supporting.reduce((sum,ev)=>sum+evidenceScore(ev),0)/supporting.length:clamp01(h.confidence),falsifierPenalty=h.falsifier?(h.falsifierTested?0:.08):.2;return {type:'HYPOTHESIS',id:h.id,label:h.statement,confidence:clamp01(supportScore-falsifierPenalty),falsifier:h.falsifier||null,falsifierTested:Boolean(h.falsifierTested)};});
 const contradictionLinks=contradictions.map(c=>({type:'CONTRADICTION',id:c.id,label:c.type,severity:c.severity,status:c.status,confidence:c.severity==='high'?.9:c.severity==='medium'?.6:.3}));
 const decisionLinks=decisions.map(d=>{const linked=(d.linkedHypothesisIds||[]).map(id=>hypothesisById.get(id)).filter(Boolean),confidence=linked.length?linked.reduce((sum,h)=>sum+clamp01(h.confidence),0)/linked.length:.35;return {type:'DECISION',id:d.id,label:d.title,state:d.state,confidence};});
 const verified=evidence.filter(x=>x.humanVerified||x.status==='FACT').length,independentGroups=new Set(trace.flatMap(t=>t.sources.map(sourceIdentity))).size;
 const unlinkedEvidence=evidence.filter(x=>!relationships.some(r=>(r.evidenceIds||[]).includes(x.id))&&!hypotheses.some(h=>[...(h.evidenceFor||[]),...(h.evidenceAgainst||[])].includes(x.id))).length,untestedFalsifiers=hypotheses.filter(x=>x.falsifier&&!x.falsifierTested).length,unsupportedRelationships=relationships.filter(r=>!(r.evidenceIds||[]).length).length,openContradictions=contradictions.filter(x=>x.status==='open').length;
 const gaps=[];if(!verified)gaps.push({code:'NO_VERIFICATION',severity:'high',message:'Claims exist but none are human-verified.'});if(independentGroups<2)gaps.push({code:'SOURCE_DEPENDENCY',severity:'medium',message:'Evidence has fewer than two independent source groups; repeated reporting may share the same origin.'});if(trace.some(t=>t.sourceCount===0))gaps.push({code:'NO_PROVENANCE',severity:'high',message:'At least one evidence item has no attached source.'});if(unlinkedEvidence)gaps.push({code:'ORPHAN_EVIDENCE',severity:'medium',message:`${unlinkedEvidence} evidence item(s) are not connected to a relationship or hypothesis.`});if(untestedFalsifiers)gaps.push({code:'UNTESTED_FALSIFIER',severity:'medium',message:`${untestedFalsifiers} falsifier(s) are defined but not tested.`});if(unsupportedRelationships)gaps.push({code:'UNSUPPORTED_LINK',severity:'high',message:`${unsupportedRelationships} relationship(s) have no explicit evidence support.`});if(openContradictions)gaps.push({code:'OPEN_CONTRADICTION',severity:'high',message:`${openContradictions} contradiction(s) remain open.`});if(hypotheses.length&&!decisions.length)gaps.push({code:'DECISION_GAP',severity:'low',message:'Hypotheses exist without a decision record.'});
 const integrity=Math.round(clamp01((verified/Math.max(1,evidence.length))*.30+Math.min(1,independentGroups/2)*.20+(trace.every(t=>t.sourceCount>0)?1:0)*.15+(1-Math.min(1,unsupportedRelationships/Math.max(1,relationships.length)))*.15+(1-Math.min(1,openContradictions/Math.max(1,contradictions.length)))*.20)*100);
 const base={nodes:[...evidenceLinks,...relationshipLinks,...hypothesisLinks,...contradictionLinks,...decisionLinks],trace,gaps,integrity,counts:{sources:sources.length,evidence:evidence.length,entities:entities.length,relationships:relationships.length,hypotheses:hypotheses.length,contradictions:contradictions.length,decisions:decisions.length,verified,independentGroups},nextAction:gaps[0]?.message||'Matrix baseline is clean; test temporal consistency and independence before approval.'};return {...base,daid2:buildDAID2(state,base)};
}
