export const STATUS=Object.freeze({FACT:'FACT',INFERENCE:'INFERENCE',ASSUMPTION:'ASSUMPTION',UNKNOWN:'UNKNOWN',CONTESTED:'CONTESTED'});
export const ENTITY_TYPES=Object.freeze(['person','organization','company','asset','location','event','unknown']);
export const DECISION_STATES=Object.freeze(['draft','review','approved','rejected','superseded']);
export const FALSIFIER_PROVENANCE=Object.freeze(['ANALYST_DECLARED','EVIDENCE_BACKED']);
export const AI_VERIFICATION_PROVENANCE=Object.freeze(['ANALYST_DECLARED','EVIDENCE_BACKED']);
export function id(prefix='id'){return `${prefix}_${crypto.randomUUID()}`;}
export function now(){return new Date().toISOString();}
export function clampConfidence(value,fallback=.5){const n=Number(value);return Number.isFinite(n)?Math.min(1,Math.max(0,n)):fallback;}
export function createCase(input={}){return {id:input.id||id('case'),title:input.title||'Untitled investigation',objective:input.objective||'',priority:input.priority||'medium',status:input.status||'open',createdAt:input.createdAt||now(),updatedAt:now(),investigationLanguage:input.investigationLanguage||'en',searchLanguages:Array.isArray(input.searchLanguages)?input.searchLanguages:['en'],reportLanguage:input.reportLanguage||'en'};}
export function createSource(input={}){return {id:input.id||id('src'),name:input.name||'Unknown source',type:input.type||'web',locator:input.locator||'',url:input.url||input.locator||'',publisher:input.publisher||'',author:input.author||'',publishedAt:input.publishedAt||'',accessedAt:input.accessedAt||now(),reliability:clampConfidence(input.reliability),independenceGroup:input.independenceGroup||'',parentSourceId:input.parentSourceId||input.derivedFromSourceId||'',provenance:input.provenance||'',capturedAt:input.capturedAt||now(),originalLanguage:input.originalLanguage||input.language||''};}
export function createEvidence(input={}){const aiAssisted=Boolean(input.aiAssisted),requestedStatus=input.status||STATUS.UNKNOWN,status=aiAssisted&&requestedStatus===STATUS.FACT?STATUS.INFERENCE:requestedStatus,sourceIds=Array.isArray(input.sourceIds)?input.sourceIds:(input.sourceId?[input.sourceId]:[]),verification=input.aiVerification&&typeof input.aiVerification==='object'?input.aiVerification:null;return {id:input.id||id('ev'),caseId:input.caseId||'',sourceId:sourceIds[0]||'',sourceIds,title:input.title||'Untitled evidence',kind:input.kind||'observation',claim:input.claim||'',originalText:input.originalText??(input.claim||''),originalLanguage:input.originalLanguage||input.language||'',translatedLanguages:Array.isArray(input.translatedLanguages)?input.translatedLanguages:[],translationStatus:input.translationStatus||'NOT_TRANSLATED',translations:Array.isArray(input.translations)?input.translations:[],whatProves:input.whatProves||'',doesNotProve:input.doesNotProve||'',entityIds:Array.isArray(input.entityIds)?input.entityIds:[],corroboratingSourceIds:Array.isArray(input.corroboratingSourceIds)?input.corroboratingSourceIds:[],contradictingSourceIds:Array.isArray(input.contradictingSourceIds)?input.contradictingSourceIds:[],locator:input.locator||'',status,confidence:clampConfidence(input.confidence),observedAt:input.observedAt||now(),capturedAt:input.capturedAt||now(),aiAssisted,humanVerified:Boolean(input.humanVerified),aiVerification:verification?{provenance:AI_VERIFICATION_PROVENANCE.includes(verification.provenance)?verification.provenance:'ANALYST_DECLARED',method:String(verification.method||''),evidenceIds:Array.isArray(verification.evidenceIds)?verification.evidenceIds:[],note:String(verification.note||''),verifiedAt:verification.verifiedAt||''}:null,notes:input.notes||''};}
export function createEntity(input={}){return {id:input.id||id('ent'),type:ENTITY_TYPES.includes(input.type)?input.type:'unknown',name:input.name||'Unnamed entity',aliases:Array.isArray(input.aliases)?input.aliases:[],notes:input.notes||''};}
export function createRelationship(input={}){return {id:input.id||id('rel'),caseId:input.caseId||'',fromEntityId:input.fromEntityId||'',toEntityId:input.toEntityId||'',type:input.type||'associated_with',evidenceIds:Array.isArray(input.evidenceIds)?input.evidenceIds:[],confidence:clampConfidence(input.confidence),status:input.status||STATUS.INFERENCE};}
export function createHypothesis(input={}){const falsifierTest=input.falsifierTest&&typeof input.falsifierTest==='object'?input.falsifierTest:null;return {id:input.id||id('hyp'),caseId:input.caseId||'',statement:input.statement||'',status:input.status||'untested',evidenceFor:Array.isArray(input.evidenceFor)?input.evidenceFor:[],evidenceAgainst:Array.isArray(input.evidenceAgainst)?input.evidenceAgainst:[],confidence:clampConfidence(input.confidence),falsifier:input.falsifier||'',falsifierTested:Boolean(input.falsifierTested),falsifierResult:input.falsifierResult||'untested',falsifierTest:falsifierTest?{provenance:FALSIFIER_PROVENANCE.includes(falsifierTest.provenance)?falsifierTest.provenance:'ANALYST_DECLARED',method:String(falsifierTest.method||''),evidenceIds:Array.isArray(falsifierTest.evidenceIds)?falsifierTest.evidenceIds:[],note:String(falsifierTest.note||''),testedAt:falsifierTest.testedAt||''}:null,updatedAt:now()};}
export function createDecision(input={}){return {id:input.id||id('dec'),caseId:input.caseId||'',title:input.title||'Untitled decision',statement:input.statement||'',state:DECISION_STATES.includes(input.state)?input.state:'draft',rationale:input.rationale||'',linkedHypothesisIds:Array.isArray(input.linkedHypothesisIds)?input.linkedHypothesisIds:[],riskAcceptance:input.riskAcceptance||'',owner:input.owner||'local-user',createdAt:input.createdAt||now(),updatedAt:now()};}
export function createContradiction(input={}){return {id:input.id||id('con'),caseId:input.caseId||'',type:input.type||'claim_conflict',severity:input.severity||'medium',leftEvidenceId:input.leftEvidenceId||'',rightEvidenceId:input.rightEvidenceId||'',explanation:input.explanation||'',status:input.status||'open',createdAt:now()};}
export function createAuditEvent(input={}){return {id:input.id||id('audit'),action:input.action||'unknown',objectType:input.objectType||'',objectId:input.objectId||'',actor:input.actor||'local-user',timestamp:input.timestamp||now(),details:input.details||''};}
