export const TEMPORAL_TYPES=Object.freeze({TEMPORAL_DISCREPANCY:'TEMPORAL_DISCREPANCY',IDENTITY_CONTINUITY:'IDENTITY_CONTINUITY',STATE_CHANGE:'STATE_CHANGE'});
const text=v=>String(v??'').trim().toLowerCase();
const dateOf=e=>e?.observedAt||e?.capturedAt||e?.createdAt||'';
const time=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?0:d.getTime()};
const explicitIds=e=>[].concat(e?.stableIdentifiers||e?.stableIdentifier||e?.identifiers||[]).map(v=>String(v)).filter(Boolean);
const embeddedIds=e=>{const s=`${e?.locator||''} ${e?.claim||''}`;const out=[];const patterns=[/\bIMO\s*[:#-]?\s*(\d{7})\b/ig,/\bMMSI\s*[:#-]?\s*(\d{9})\b/ig,/\b(?:LEI|ICAO)\s*[:#-]?\s*([A-Z0-9-]{6,30})\b/ig];for(const r of patterns){for(const m of s.matchAll(r))out.push(`${m[0].split(/[:#-]?\s*/)[0].toUpperCase()}:${m[1]}`)}return out};
export function extractStableIdentifiers(e){return [...new Set([...explicitIds(e),...embeddedIds(e)].map(text).filter(Boolean))]}
function fieldSnapshot(e){if(e?.temporalFields&&typeof e.temporalFields==='object')return e.temporalFields;if(e?.temporalField)return {[e.temporalField]:e.value??e.claim};if(e?.field)return {[e.field]:e.value??e.claim};return {claim:e?.claim??''}}
function keys(a,b){return [...new Set([...Object.keys(fieldSnapshot(a)),...Object.keys(fieldSnapshot(b))])].filter(Boolean)}
export function temporalAnalysis(state,{caseId=null}={}){const evidence=(state?.evidence||[]).filter(e=>!caseId||e.caseId===caseId),groups=new Map(),results=[];for(const e of evidence){for(const id of extractStableIdentifiers(e)){const k=`${e.caseId||'global'}|${id}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(e)}}for(const items of groups.values()){const ordered=[...new Map(items.map(e=>[e.id,e])).values()].sort((a,b)=>time(dateOf(a))-time(dateOf(b)));for(let i=0;i<ordered.length-1;i++){const a=ordered[i],b=ordered[i+1],fa=fieldSnapshot(a),fb=fieldSnapshot(b);for(const field of keys(a,b)){const av=text(fa[field]),bv=text(fb[field]);if(!av||!bv||av===bv)continue;results.push({type:TEMPORAL_TYPES.STATE_CHANGE,caseId:a.caseId,leftEvidenceId:a.id,rightEvidenceId:b.id,stableIdentifiers:extractStableIdentifiers(a).filter(id=>extractStableIdentifiers(b).includes(id)),field,severity:'medium',earlierDate:dateOf(a),laterDate:dateOf(b),from:fa[field],to:fb[field],message:`Stable identifier retained while ${field} changed over time. Treat this as a temporal state change, not automatically as a contradiction.`})}}}return dedupe(results)}
function dedupe(items){const seen=new Set();return items.filter(x=>{const k=[x.caseId,x.leftEvidenceId,x.rightEvidenceId,x.field,x.type].join('|');if(seen.has(k))return false;seen.add(k);return true})}
export function buildTemporalTimeline(state,caseId){return(state?.evidence||[]).filter(e=>!caseId||e.caseId===caseId).sort((a,b)=>time(dateOf(a))-time(dateOf(b))).map(e=>({id:e.id,date:dateOf(e),title:e.title,claim:e.claim,sourceId:e.sourceId,status:e.status,stableIdentifiers:extractStableIdentifiers(e)}))}
