import { getLocale,setLocale,supportedLocales,translate } from './core/i18n.js';
const $=id=>document.getElementById(id);
const original=new WeakMap();
function remember(node){if(!original.has(node))original.set(node,node.nodeValue.trim());return original.get(node);}
function translateDom(locale){document.documentElement.lang=locale;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){const raw=remember(node);if(!raw)continue;const t=translate(raw,locale);if(t!==raw){const leading=node.nodeValue.match(/^\s*/)?.[0]||'';const trailing=node.nodeValue.match(/\s*$/)?.[0]||'';node.nodeValue=leading+t+trailing;}else if(locale==='en'&&node.nodeValue!==raw){node.nodeValue=raw;}}
for(const el of document.querySelectorAll('[placeholder],[aria-label],[title]')){for(const attr of ['placeholder','aria-label','title']){const value=el.getAttribute(attr);if(value===null)continue;const key=el.dataset[`i18n${attr==='aria-label'?'Aria':attr[0].toUpperCase()+attr.slice(1)}`]||value;el.dataset[`i18n${attr==='aria-label'?'Aria':attr[0].toUpperCase()+attr.slice(1)}`]=key;el.setAttribute(attr,translate(key,locale));}}}
function installSelector(){if($('languageControl'))return;const status=document.querySelector('.status');if(!status)return;const wrap=document.createElement('label');wrap.id='languageControl';wrap.title='Interface language';wrap.style.cssText='display:inline-flex;align-items:center;gap:7px;margin-left:8px';const icon=document.createElement('span');icon.textContent='◉';icon.setAttribute('aria-hidden','true');const select=document.createElement('select');select.id='localeSelect';select.setAttribute('aria-label','Interface language');select.style.cssText='background:#071318;color:var(--text);border:1px solid var(--line);border-radius:7px;padding:6px 8px;font:10px system-ui;outline:none';for(const l of supportedLocales()){const o=document.createElement('option');o.value=l.code;o.textContent=`${l.native} · ${l.code.toUpperCase()}`;select.appendChild(o);}select.value=getLocale();select.addEventListener('change',()=>setLocale(select.value));wrap.append(icon,select);status.appendChild(wrap);}
function boot(){installSelector();translateDom(getLocale());window.addEventListener('occ:locale',e=>translateDom(e.detail.locale));const observer=new MutationObserver(()=>{clearTimeout(window.__i18nTimer);window.__i18nTimer=setTimeout(()=>translateDom(getLocale()),40)});observer.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
