import { shannonEntropy,fileSignature,timestampAnomalies,provenanceDrift,sourceIndependenceMatrix,negativeSpaceAnalysis,narrativeDelta,impossibilityCheck } from './forensics.js';
import { parseChat,behavioralProfile,conversationDNA,coordinationDetector,narrativeDrift,claimTrap,ghostEntitySignals } from './behavioral-forensics.js';
import { loadState,getActiveCaseId,addRecord } from '../core/store.js';
import { findingToEvidence } from './forensic-bridge.js';

const $=id=>document.getElementById(id);
const state={};
const text=(id,v)=>{const e=$(id);if(e)e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)};
function show(){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='forensicsView'));document.querySelectorAll('.nav button').forEach(x=>{const on=x.dataset.view==='forensics';x.classList.toggle('active',on);x.setAttribute('aria-current',on?'page':'false')});if($('pageTitle'))$('pageTitle').textContent='Forensics / Signal Lab';if($('pageSub'))$('pageSub').textContent='Local forensic instruments. Findings remain analytical signals until human review.';history.replaceState(null,'','#forensics')}
function cardResult(id,result,kind){state[id]=result;text(id,result);const host=$(id);if(!host)return;host.dataset.kind=kind;let b=host.parentElement?.querySelector('.promote-finding');if(!b){b=document.createElement('button');b.className='button promote-finding';b.textContent='Review → Evidence';host.parentElement?.appendChild(b);b.addEventListener('click',()=>promote(id));}}
function promote(id){const finding=state[id];const caseId=getActiveCaseId(loadState());if(!caseId){alert('Create or focus a case first.');return}if(finding==null){alert('Run the analysis first.');return}const claim=typeof finding==='string'?finding:(finding.summary||finding.signal||finding.type||`${$(id)?.dataset.kind||'forensic'} finding`);const ev=findingToEvidence({caseId,analysisType:$(id)?.dataset.kind||'forensic',title:`Forensic signal · ${$(id)?.dataset.kind||'analysis'}`,claim,details:JSON.stringify(finding,null,2)});addRecord('evidence',ev);document.dispatchEvent(new CustomEvent('occ:state-changed',{detail:{source:'forensics',evidenceId:ev.id}}));const host=$(id);if(host)host.insertAdjacentHTML('beforeend','\n\nPERSISTED → Evidence · UNKNOWN · confidence 0');}
function json(id){return JSON.parse($(id).value)}
function boot(){if($('forensicsView'))return;const host=$('main')||document.body,v=document.createElement('section');v.id='forensicsView';v.className='view workspace';v.innerHTML=`<div class="toolbar"><div><h2>FORENSICS / SIGNAL LAB</h2><p class="sub">Local analytical instruments. Every promoted finding enters the evidence ledger as UNKNOWN until human review.</p></div><span class="tag ok">LOCAL-FIRST</span></div><div class="tool-grid">
<article class="tool-card"><h3>FILE SIGNATURE + ENTROPY</h3><p>Inspect magic bytes and entropy locally.</p><input id="fxFile" type="file"><div id="fxOut" class="tool-result">Select a file.</div></article>
<article class="tool-card"><h3>TEMPORAL ANOMALY</h3><textarea id="fxTimes" placeholder="One timestamp per line"></textarea><button class="button primary" id="fxTimesRun">Analyze timeline</button><div id="fxTimesOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>PROVENANCE DRIFT</h3><textarea id="fxProv" placeholder='JSON: [{"source":"A","author":"X","hash":"1"}]'></textarea><button class="button primary" id="fxProvRun">Detect drift</button><div id="fxProvOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>SOURCE INDEPENDENCE</h3><textarea id="fxSources" placeholder='JSON: [{"name":"A","origin":"Org 1"}]'></textarea><button class="button primary" id="fxSourcesRun">Map independence</button><div id="fxSourcesOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>NEGATIVE SPACE</h3><div class="tool-row"><textarea id="fxExpected" placeholder="Expected signal 1"></textarea><textarea id="fxObserved" placeholder="Observed signal 1"></textarea></div><button class="button primary" id="fxNegRun">Find missing signals</button><div id="fxNegOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>NARRATIVE DELTA</h3><div class="tool-row"><textarea id="fxBefore" placeholder="Earlier narrative"></textarea><textarea id="fxAfter" placeholder="Later narrative"></textarea></div><button class="button primary" id="fxDeltaRun">Compute delta</button><div id="fxDeltaOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>TEMPORAL-GEO IMPOSSIBILITY</h3><textarea id="fxEvents" placeholder='JSON: [{"time":"2026-01-01T10:00:00Z","lat":45,"lon":12}]'></textarea><button class="button primary" id="fxImpossibleRun">Test sequence</button><div id="fxImpossibleOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>CHAT FORENSICS</h3><textarea id="fxChat" placeholder="2026-09-10T10:00:00Z Alice: First message\n2026-09-10T10:02:00Z Bob: Reply"></textarea><button class="button primary" id="fxChatRun">Analyze chat</button><div id="fxChatOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>BEHAVIORAL SIGNAL PROFILE</h3><textarea id="fxBehavior" placeholder="Alice: I need this now?\nAlice: https://example.org\nBob: I will check."></textarea><button class="button primary" id="fxBehaviorRun">Build profile</button><div id="fxBehaviorOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>CONVERSATION DNA</h3><textarea id="fxDnaA" placeholder="Conversation sample A"></textarea><textarea id="fxDnaB" placeholder="Conversation sample B"></textarea><button class="button primary" id="fxDnaRun">Compare samples</button><div id="fxDnaOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>COORDINATION DETECTOR</h3><textarea id="fxCoord" placeholder='JSON: [{"name":"A","events":[{"time":"2026-09-10T10:00:00Z"}]},{"name":"B","events":[{"time":"2026-09-10T10:00:30Z"}]}]'></textarea><button class="button primary" id="fxCoordRun">Detect timing clusters</button><div id="fxCoordOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>NARRATIVE DRIFT</h3><textarea id="fxDrift" placeholder='JSON: [{"source":"A","text":"I was at home"},{"source":"B","text":"I was at work"}]'></textarea><button class="button primary" id="fxDriftRun">Trace drift</button><div id="fxDriftOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>CLAIM TRAP</h3><textarea id="fxClaim" placeholder="Claim"></textarea><textarea id="fxClaimEvidence" placeholder='JSON: [{"claim":"supporting text"}]'></textarea><button class="button primary" id="fxClaimRun">Stress-test claim</button><div id="fxClaimOut" class="tool-result">Awaiting input.</div></article>
<article class="tool-card"><h3>GHOST ENTITY RADAR</h3><textarea id="fxEntities" placeholder='JSON: [{"id":"e1","name":"Person A","type":"person"}]'></textarea><textarea id="fxEntityEvidence" placeholder='JSON: [{"entityIds":["e1"]}]'></textarea><button class="button primary" id="fxGhostRun">Find unlinked entities</button><div id="fxGhostOut" class="tool-result">Awaiting input.</div></article></div>`;const anchor=$('view-tools');if(anchor)anchor.before(v);else host.appendChild(v);const n=document.querySelector('.nav');if(n&&!n.querySelector('[data-view="forensics"]')){const b=document.createElement('button');b.dataset.view='forensics';b.textContent='◈ Forensics / Signal Lab';n.insertBefore(b,n.querySelector('[data-view="reports"]'));b.addEventListener('click',show)}
$('fxFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const bytes=new Uint8Array(await f.arrayBuffer());cardResult('fxOut',`${JSON.stringify(fileSignature(bytes),null,2)}\nEntropy: ${shannonEntropy(bytes)} bits/byte\nSignal only: entropy does not prove encryption/compression.` ,'file_signature');});
$('fxTimesRun').onclick=()=>cardResult('fxTimesOut',timestampAnomalies($('fxTimes').value.split(/\r?\n/).filter(Boolean)),'temporal_anomaly');
$('fxProvRun').onclick=()=>safe('fxProvOut','provenance_drift',()=>provenanceDrift(json('fxProv')));$('fxSourcesRun').onclick=()=>safe('fxSourcesOut','source_independence',()=>sourceIndependenceMatrix(json('fxSources')));$('fxNegRun').onclick=()=>cardResult('fxNegOut',negativeSpaceAnalysis({expected:$('fxExpected').value.split(/\r?\n/).filter(Boolean),observed:$('fxObserved').value.split(/\r?\n/).filter(Boolean)}),'negative_space');$('fxDeltaRun').onclick=()=>cardResult('fxDeltaOut',narrativeDelta($('fxBefore').value,$('fxAfter').value),'narrative_delta');$('fxImpossibleRun').onclick=()=>safe('fxImpossibleOut','temporal_geo_impossibility',()=>impossibilityCheck(json('fxEvents')));$('fxChatRun').onclick=()=>cardResult('fxChatOut',parseChat($('fxChat').value),'chat_forensics');$('fxBehaviorRun').onclick=()=>cardResult('fxBehaviorOut',behavioralProfile(parseChat($('fxBehavior').value).messages),'behavioral_profile');$('fxDnaRun').onclick=()=>cardResult('fxDnaOut',conversationDNA(parseChat($('fxDnaA').value).messages,parseChat($('fxDnaB').value).messages),'conversation_dna');$('fxCoordRun').onclick=()=>safe('fxCoordOut','coordination_detector',()=>coordinationDetector(json('fxCoord')));$('fxDriftRun').onclick=()=>safe('fxDriftOut','narrative_drift',()=>narrativeDrift(json('fxDrift')));$('fxClaimRun').onclick=()=>safe('fxClaimOut','claim_trap',()=>claimTrap($('fxClaim').value,json('fxClaimEvidence')));$('fxGhostRun').onclick=()=>safe('fxGhostOut','ghost_entity',()=>ghostEntitySignals(json('fxEntities'),json('fxEntityEvidence')));if(location.hash==='#forensics')show();}
function safe(outId,kind,fn){try{cardResult(outId,fn(),kind)}catch(e){text(outId,'ERROR: '+e.message)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
